networks:
  # define network to communicate between container 
  Ecommerce_net:
    name: Ecommerce_net
    driver: bridge

volumes:
  #blind volume for persistance storage
  mysql_data_vol:
  ecommerce_backend_data_vol:


services:
  #define service or container 
  mysql_service:
    image: mysql:8.0
    container_name: mysql_Ecommerce
    networks:
      - Ecommerce_net
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=ecommerce
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ecommerce_backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_backend_service
    env_file:
      - .env
    networks:
      - Ecommerce_net
    ports:
      - "8000:8000"
    volumes:
      - ecommerce_backend_data_vol:/Ecommerce/backend/developer/backend/node_modules
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=ecommerce

    depends_on:
      mysql_service:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "
        npm install &&
        cd src &&
        npx sequelize-cli db:create --env development --config config/docker-config.json &&
        npx sequelize-cli db:migrate --env development --config config/docker-config.json &&
        npx sequelize-cli db:seed:all --env development --config config/docker-config.json &&
        cd .. &&
        npm start
      "
